### PR TITLE
Revert "Add a &nbsp; after timestamp"

### PR DESCRIPTION
**Pull request by dbkr**
Reverts vector-im/riot-web#3046

This is adding a visible '&nbsp;'...

### CODE REVIEW

**Comment by rubo77** [comment]
What do you mean?

The idea was to add a space, so if you copy paste a conversation the time does not stick to the first word any more

**Comment by t3chguy** [comment]
@rubo77 
image

**Comment by rubo77** [comment]
By the time I created the pr this behaviour was different.

What about now, if you copy paste a conversation do you have a space after the timestamp or not?

And maybe it would correctly be changed here if you just add a space here, not a non breaking space.

**Comment by t3chguy** [comment]
```
12:22PM
Matthew: Ah, sorry I caught you in a bad time. Couled I ask you to delete my account (this one) when you get the chance? I forgot my password so I can't do it by myself.
```

right now when I copy and paste in the Desktop app I have a new line between the timestamp and the content

**Comment by rubo77** [comment]
And in Firefox? I think the problem was only there

**Comment by rubo77** [comment]
And I didn't is the 12h format

**Pull request merged**
