### PR TITLE
Add a secondary dark theme (named blueshine)

### PR DESCRIPTION
**Pull request by MTRNord**
Hi I made the last few days a new dark theme. It uses the base code of the status.im css but got modified. Below are some screenshots of the theme. There is a matrix-react-sdk here: https://github.com/matrix-org/matrix-react-sdk/pull/1941

~~This still says WIP because I think I missed some colors still as I didn't yet had to change all css variables. But the defaults might be fine~~

Feel free to tell me opinions or to say that another theme isn't wanted (I fully respect the Matrix team on the decision about theme PRs)

Signed-Off-By: Marcel Radzio <mtrnord1 [at] gmail.com>

grafik

grafik

grafik

grafik

grafik

grafik

grafik

grafik

grafik

grafik

### CODE REVIEW

**Comment by tidux** [comment]
The message area is still too narrow horizontally.  Something like https://userstyles.org/styles/159824/riot-im-better-layout could help.

**Comment by MTRNord** [comment]
@tidux that is not related to this theme. It is a known issue please see #1371 This is a community theme So I will not mess with that in here.

**Comment by MTRNord** [comment]
Oh and note for the Devs of the core team who are going to do the review later on: I have the intention to later on port this to the new redisgn as soon as we got the first real demo in Riot :) I will try to maintain this as best as possible in the future

**Comment by MTRNord** [comment]
This PR should be review ready

**Comment by skylord123** [comment]
I actually really like this theme. As a user of the current dark theme I would switch to this if it was merged.

**Comment by MTRNord** [comment]
Because of having a lot of less time recently I am not certain if I will port this to the new design. Might be that this PR does not get updated.

**Pull request closed without merging**
