### PR TITLE
Themes defined in riot-web config.json

### PR DESCRIPTION
**Pull request by dtygel**
With this PR and also https://github.com/matrix-org/matrix-react-sdk/pull/876 , themes aren't hardcoded in UserSettings anymore. Now any developper can create his/her themes and add them to config.json in riot-web. Important: the **first** theme declared in config.json will be the default for newcomers and users who didn't define their theme in personal settings.

### CODE REVIEW

**Comment by dbkr** [comment]
I've made some comment over in the react sdk PR.

**Comment by tessgadwa** [comment]
We still need a better way to store .svgs and other background graphics for individual themes. Will submit as a separate issue and/or PR, but believe this is relevant to this change as well.

**Comment by ara4n** [comment]
looks like i've totally missed this PR ever existing - sorry :(  Some of it has been overtaken by events (the ability to define the default theme in the config.json) - but the core idea of being able to specify the list of allowed themes in config.json is still valid.  Someone needs to rescue it and merge it in.  Sorry for blocking it :(

**Comment by turt2live** [comment]
It looks like the react-sdk side was closed for this. Thanks again for the PR, though we've gone a different direction for the theme support.

See https://github.com/matrix-org/matrix-react-sdk/pull/876#issuecomment-516802909 for why the react-sdk PR was closed.

**Pull request closed without merging**
