### PR TITLE
stage-1 rebrand vector->riot

### PR DESCRIPTION
**Pull request by t3chguy**
for #3613

Signed-off-by: Michael Telatynski <7t3chguy@gmail.com>

### CODE REVIEW

**Comment by dbkr** [comment]
Personally, I'm very much in favour of the internal codename remaining as vector: I don't see any value in renaming non-user facing internals to match the brand: it will be another way to introduce bugs.

**Comment by t3chguy** [comment]
@dbkr thats fair enough, I'm of a similar mindset, @lampholder seems of different opinion

**Comment by ara4n** [comment]
yes, please let's not waste time doing s/Vector/Riot/ on all the classes and variable names.  (Just as most of macOS's internal API prefixes are still NS for NextStep... :D).  Agreed that user-facing tarballs etc should be named correctly though.

**Comment by t3chguy** [comment]
@ara4n so you just want the https://github.com/vector-im/riot-web/pull/3798/files#diff-188acaa55654fd2e210e1da372302214 changes?

**Comment by lampholder** [comment]
>@dbkr thats fair enough, I'm of a similar mindset, @lampholder seems of different opinion

Er, do I?

**Comment by t3chguy** [comment]
@lampholder misread https://github.com/vector-im/riot-web/issues/3613#issuecomment-295845689
neeeever mind

**Comment by t3chguy** [comment]
closed in favour of #3894

**Pull request closed without merging**
