### PR TITLE
Correct the copying of e-mail addresses in the electron app

### LINKED ISSUE #7937: Copied e-mail addresses are prefixed with `mailto:`
### Description

When I copy an e-mail address (e.g. firstname.lastname@example.com) by rightclicking on it -> Copy Link Address, my clipboard contains `mailto:firstname.lastname@example.com` afterwards. The `mailto:` that prefixes this is superfluous and I have to manually remove it when I want to paste the address somewhere else, which is annoying.

### Steps to reproduce

- Send a message containing an e-mail address in a chat message, e.g. `firstname.lastname@example.com`
- Right click the address as it is displayed in Riot
- Click on "Copy Link Address"
- Paste it anywhere, and notice the `mailto:` prefix

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Ubuntu 18.04
- **Version**: 0.17.6

### PR DESCRIPTION
**Pull request by t3chguy**
Fixes #7937 

Changes the labels all the match casing of Chrome.
Fixes a small typo in a comment.

Signed-off-by: Michael Telatynski <7t3chguy@gmail.com>

### CODE REVIEW

**Comment by jryans** [comment]
(It is a bit surprising that this PR shows my develop commit for `SdkConfig`, while other develop -> experimental merges did not...)

**Comment by turt2live** [comment]
That change apparently hasn't made it to experimental I guess :(

I'm generally fine with ignoring the problem though and reviewing the actual changes at hand

**Comment by t3chguy** [comment]
I/someone can rebase if needs be.

**Comment by t3chguy** [comment]
Does it need rebasing to get out that other commit or not?

**Comment by turt2live** [comment]
I don't think it does. It's a small change that should be on experimental anyways: this is just the vessel to get it there

**Comment by jryans** [comment]
(The actual textual change made in the other commit is [already present](https://github.com/vector-im/riot-web/commit/05f9cf453dbd773666404679aee621a43323652d) on experimental. It was just made via different commits for develop and experimental, which seems to be confusing things. Should be safe to ignore.)

**Pull request merged**
