### PR TITLE
Allow Electron to zoom with CommandOrControl+=

### LINKED ISSUE #7721: Electron: additionally map ctrl (or cmd) + '=' to zoom in
### Description

In the app, I can only zoom out, and not in. So `cmd`+`-`, and `cmd`+`0` work, but just not `cmd`+`+`.

### Version information

- **Platform**: Desktop
- **OS**: macOS Mojave 10.14.1
- **Version**: 0.17.6

### LINKED ISSUE #15496: Reactions are
### Description

Describe here the problem that you are experiencing, or the feature you are requesting.

### Steps to reproduce

- For bugs, list the steps
- that reproduce the bug
- using hyphens as bullet points

Describe how what happens differs from what you expected.

Logs being sent: yes/no

### Version information

- **Platform**: web (in-browser) or desktop?

For the web app:

- **Browser**: Chrome, Safari, Firefox? which version?
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **URL**: develop.element.io / app.element.io / somewhere else? If a private server, what version of Element Web?

For the desktop app:

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **Version**: 1.x.y

### PR DESCRIPTION
**Pull request by aaronraimist**
Fixes #7721

This creates two menu items which looks bad but [setting the second one to `visible: false` seems to disable it too](https://github.com/electron/electron/issues/15496#issuecomment-460001112). 😡 

screen shot 2019-02-02 at 3 55 48 pm

Hopefully someone will actually solve https://github.com/electron/electron/issues/15496 upstream

### CODE REVIEW

**Comment by aaronraimist** [comment]
I don't know a lot about Electron but it seems like you can't do this very well. I guess you can do 
https://github.com/electron/electron/issues/1334#issuecomment-310920998 but I can't get it to work. Electron itself only really supports creating global (affects the app even when the user isn't using the app) shortcuts without a menu item.

> Given the workarounds above, we believe this module is better implemented in userland (ex. the excellent [electron-localshortcut](https://github.com/parro-it/electron-localshortcut) and thus i'm going to label this a `wontfix`.

https://github.com/electron/electron/issues/1334#issuecomment-423871405

**Comment by aaronraimist** [comment]
The other alternative is to get rid of the Shift+Command+Plus shortcut

**Comment by jryans** [comment]
I'd prefer to find a way to have only one menu item with ⌘+ displayed, while still accepting both Cmd-Plus and Cmd-Shift-Plus, as that's how most other native apps appear to handle this issue.

Looking at Atom, that's what they seem to do, but of course their version is much more complex since they support user remappable shortcuts.

It's a bit sad that this is so hard to solve with Electron... 😓

**Comment by jryans** [comment]
> The other alternative is to get rid of the Shift+Command+Plus shortcut, the menu item will still look "wrong" but at least there will only be one

Maybe that's an okay compromise, since it seems unreasonably hard to do the right thing in Electron.

**Comment by aishahsofea** [comment]
Use `CmdOrCtrl+Plus` to make sure that the shortcut icon is displayed correctly

**Pull request merged**
