### PR TITLE
Mirror local video feed (fixes #2883)

### LINKED ISSUE #2883: Own webcam preview in video call is not mirrored
In a video call, the webcam preview in the small box should be like looking at a mirror.

### PR DESCRIPTION
**Pull request by TheLastProject**
```Signed-off-by: Sylvia van Os <sylvia@hackerchick.me>```

This simply does a CSS transformation on the local video to horizontally mirror it.

### CODE REVIEW

**Comment by ara4n** [comment]
it's weird - i've never noticed this as a problem. and i think it'd be a bit strange for text to be appear flipped in the local preview. What is the rationale here? Just to make things look more like a mirror?  Wouldn't it be better to preview to look as the other user will see you, rather than how you see yourself when you look in the mirror?

(related: *excellent* explanation of the weirdness of mirrors can be found at http://www.cs.bham.ac.uk/research/projects/cogaff/misc/magic-mirrors.html)

**Comment by TheLastProject** [comment]
The idea is indeed to make it more like a mirror because that's the default of all video/camera apps I've ever seen and Riot being the odd one out makes looking at your own video feed rather disorienting.

Try to do basic tasks while looking at your video feed like grabbing something you can see on your local feed. Without this patch, I pretty much always use the wrong arm to try to reach it. I also always move myself to the wrong side if I am not properly centered in the feed and try to center myself or if I try to hold something up to the camera so the other can see. Things like that.

**Comment by xuhdev** [comment]
At least please make this to be an option -- [some people seem to want the other way as well](https://superuser.com/q/201439/139328).

**Comment by lukebarnard1** [comment]
@TheLastProject would you be willing to make this an optional feature? by adding a setting in UserSettings?

**Comment by TheLastProject** [comment]
@lukebarnard1 Probably not something I'll be getting to any times soon as learning Riot's preference system and adding an option is a million times more complex than a single line of CSS and I don't quite have the time to study Riot's codebase that deeply. Surely won't oppose to it being an option though.

**Comment by lukebarnard1** [comment]
In that case, I shall build on this and make it optional.

**Pull request closed without merging**
