### PR TITLE
to make the windows volume mixer not explode as it can't resize icons.

### PR DESCRIPTION
**Pull request by t3chguy**
fixes 
image

Might not be the best way, probably worth @dbkr looking it over.

I hate Windows.

Signed-off-by: Michael Telatynski <7t3chguy@gmail.com>

### CODE REVIEW

**Comment by t3chguy** [comment]
Alternative is extracting the red circle badge component of the image and using the actual overlay function, that would mean another lot of canvas etc in the renderer though

**Comment by t3chguy** [comment]
Oh actually this won't work at all and only works because of my monitor being at 125% DPI Scale.

### DO NOT MERGE

**Comment by t3chguy** [comment]
This should fix it, converts png to a proper ico file, have to save it as nativeImage has no proper support for icos and can only load them form a file, can't read from buf etc

**Comment by t3chguy** [comment]
fixes #4185

**Comment by ara4n** [comment]
that's hilarious. lgtm.

**Comment by t3chguy** [comment]
Agreed, gotta love Windows ... right!?

**Pull request merged**
