### PR TITLE
[DO NOT MERGE] Optimize Webpack Performance and bundle size

### PR DESCRIPTION
**Pull request by MTRNord**
This commit does what I explained in https://github.com/vector-im/riot-web/issues/7391

It needs this PR too: https://github.com/matrix-org/matrix-react-sdk/pull/2323

Signed-off-by: Marcel Radzio <mtrnord1 [at] gmail.com>

# THIS PR MIGHT BREAK OTHER PRS! It is needed that imports of react-sdk reference src instead of lib

### CODE REVIEW

**Comment by MTRNord** [comment]
The build is expected to fail because it did not find the react-sdk PR because this PR was opened first.

A restart should fix the build failure.

**Comment by MTRNord** [comment]
I do think both tests fail because they dont find each other counter branch :( `fatal: Remote branch webpack4-optimizations not found in upstream origin`

**Comment by MTRNord** [comment]
# GOING TO REOPEN AFTER FINISHING TODO AS I MESSED UP THE HISTORY

**Comment by MTRNord** [comment]
# Tests are failing because it fails to resolve the correct compainion branch. Please test it locally first before merging.

**Comment by jryans** [comment]
@MTRNord Now that we're past 1.0, I'd like to nudge this forward, but it will need some rebasing. Are you interested in updating it, or shall I take a look?

**Comment by MTRNord** [comment]
@jyrans I can try to fix the merge issues. But I expect the CI to still fail because it doesn't find its companion branch on the sdk. You should test it locally before merging!

**Comment by jryans** [comment]
> You should test it locally before merging!

I may also re-push it as a branch on the matrix and vector repos once the rebase is ready to hopefully see the green checks there at least. CI can figure out the matching branches, but currently it doesn't work for forked repos like this yet... 😭

**Comment by MTRNord** [comment]
@jryans I just made a rebase on the new develop branch on riot-web. A rebase for the sdk is on its way

**Comment by jryans** [comment]
@MTRNord We just [added support](https://github.com/vector-im/riot-web/issues/9041) for testing matching branches from forks, so your branches here should hopefully be testable now! 😄 If you merge in https://github.com/matrix-org/matrix-react-sdk/pull/2807 and https://github.com/vector-im/riot-web/pull/9212, we should get some proper CI results here.

**Comment by MTRNord** [comment]
@jryans will do when near my PC :)

**Comment by MTRNord** [comment]
@jryans made a rebase to curent develop. Lets see if this still works liek on my local PC

**Comment by MTRNord** [comment]
Seems like it still doesnt build on CI I will investigate

**Comment by jryans** [comment]
It did find your matching branches though, so that's great to see! Hopefully the errors that remain are actual problems that can be fixed.

**Comment by MTRNord** [comment]
> 
> 
> It did find your matching branches though, so that's great to see! Hopefully the errors that remain are actual problems that can be fixed.

It seems like they are :) Working on a fix. Seems like it tries to load still from the lib folder on the react sdk somewhere. TBH the error message is not that helpful ^^

**Comment by MTRNord** [comment]
@jryans for some reason it seems to not find the src folder in the react sdk at all. Is it maybe a bug on the resolving itself?

**Comment by jryans** [comment]
> @jryans for some reason it seems to not find the src folder in the react sdk at all. Is it maybe a bug on the resolving itself?

Some errors are still `lib` paths to update it looks like:

```
ERROR in ./src/components/views/auth/VectorCustomServerDialog.js
Module not found: Error: Can't resolve 'matrix-react-sdk/lib/languageHandler' in '/workdir/src/components/views/auth'
```

However there are also `src` paths like:

```
ERROR in ./src/vector/platform/VectorBasePlatform.js
Module not found: Error: Can't resolve 'matrix-react-sdk/src/BasePlatform' in '/workdir/src/vector/platform'
```

which is I guess why you're asking? It's possible this is related to how CI currently checks out the other repos, which is different than what we do on local dev machines: CI checks out the SDKs _inside_ the riot-web directory, which means that are at a different nesting level than a local environment would use. Perhaps you can try simulating this setup locally to see if the errors happen because of it?

**Comment by MTRNord** [comment]
@jryans I can do normal build local but not test. So I guess thats a karma issue as well. I am still debugging why it happens. The paths look for node_modules/matrix-react-sdk and as they are on CI linked that path should be fine.

**Comment by MTRNord** [comment]
@jryans found the error. I have an alias to make the index.js overwritten. But that one also causes to let imports fail :/

**Comment by MTRNord** [comment]
Seems like there is a babel-loader issue too. WIll spoin up a linux to check in there. It has a different error on my dev PC so it is super hard to debug

**Comment by MTRNord** [comment]
Found the error: The import resolving on linux is different on linux than on my windows PC. And the module instead of main usage in package.json causes module.export = {} to not be accepted when importing. I will search for another way

**Comment by MTRNord** [comment]
Seems like I essentialy made this a monorepo and babel hates me for doing that. The only way I see is to upgrade babel and babel-loader in riot-web and replace .babelrc with babel.config.js and fix imports in react-sdk to allow importing files that use module.exports :( This might make this PR horrible. Means I will do that, commit it and make a new PR from scratch to clean it up.

(This would by the way fix https://github.com/vector-im/riot-web/issues/7731 as a side effect)

**Comment by MTRNord** [comment]
This PR is closed. I will reopen until I get this to build again. I guess I will make the babel upgrade a seperate PR too

**Comment by almamun-dev** [comment]
Hi, one of my client needs private instant Messaging software like whatsapp. is it possible to develop riot for a private company. Please mail me, if anyone can solve my problem. Email: haydenj951@gmail.com ll skype: almamun.dev ll Whatsapp: +8801723894682

**Pull request closed without merging**
