### PR TITLE
Fix Webpack conf

### PR DESCRIPTION
**Pull request by t3chguy**
Fixes:
```
ERROR in ./~/olm/olm.js
Module not found: Error: Cannot resolve module 'fs' in C:\Users\t3chg\WebStormProjects\riot-web\node_modules\olm
 @ ./~/olm/olm.js 18:39-52
```

### CODE REVIEW

**Comment by ara4n** [comment]
hm, by switching forward slashes for backwards slashes, doesn't this break things on unix in favour of working on windows?  or is there some voodoo happening to make it work on unix too that i'm missing?

also, i'm not keen on some of the formatting changes here (or mixing them together with the functional bit of the commit) - the long lines have been deliberately broken up in places for aesthetic clarity.  (or has eslint bullied you into this?)

**Comment by t3chguy** [comment]
It isn't switching forward slashes for backwards slashes, its providing a regex for each, so one would trigger on *nix and the other on Windows.

ESLint very much bullied me complaining about a lacking trailing comma if its split across multiple lines, I trusted its false positives in the first commit and thus the test failed spectacularly.

**Comment by t3chguy** [comment]
though the more readable approach is probably to use a character class with both forward and backward slashes and an appropriate comment

**Comment by ara4n** [comment]
oh, sorry - i completely missed that it was adding the backslash regexp rather than replacing the fwdslash one.  The character class feels miles better and is more DRYing- thanks.

**Pull request merged**
