### PR TITLE
Implement general-purpose tooltip "(?)"-style

### PR DESCRIPTION
**Pull request by lukebarnard1**
e.g.

2017-11-07-141352_247x112_scrot

### CODE REVIEW

**Comment by ara4n** [comment]
Hum. We already had mx_RoomTooltip as a generic tooltip mechanism (despite the misleading name), so i'm rather surprised that we've created an entirely new mx_Tooltip here which has entirely different CSS (and colouring and aesthetics which is now inconsistent with the existing design).  I would have expected instead to have fixed the naming on mx_RoomTooltip and extended it to support multiline descriptions (if it doesn't already).  The situation is made even messier by the fact that the dispatcher already has a generic `view_tooltip` action (hooked up to RoomTooltip).  Please yell if i am missing some consideration though?

I'd rather we didn't burn further time on a P2 non-release-blocker thing when we are trying to rush to get a release out the door, so I suggest we just merge it for now and unify all the tooltips down the road.  I'm not really sure how to suggest how to avoid this sort of misstep in future, other than trying to keep DRY and maintainability in mind, and being aware that whenever we are adding entirely new CSS for visuals which effectively already exist in the UI, we're almost certainly doing it wrong.

In terms of the code specifics it looks great, and I suggest we merge it for now.

**Comment by ara4n** [comment]
twinned with https://github.com/matrix-org/matrix-react-sdk/pull/1582

**Comment by lukebarnard1** [comment]
Yep looks like I've found a particularly bad part of the tradeoff between speed of impl. and maintainability. Sorry about that. I anticipated the modifying of the existing RoomTooltip to be more work than wrapping it and giving it a "?". 

>The situation is made even messier by the fact that the dispatcher already has a generic view_tooltip action (hooked up to RoomTooltip)

This is handled by the RoomList and doesn't seem to do much other than something specific to the RoomList.

>I'd rather we didn't burn further time on a P2 non-release-blocker thing when we are trying to rush to get a release out the door, so I suggest we just merge it for now and unify all the tooltips down the road

sgtm! My bad for trying to half-rush a p2 thing.

>maintainability in mind, and being aware that whenever we are adding entirely new CSS for visuals which effectively already exist in the UI

I guess the name `mx_RoomTooltip` and the way the existing one was already being used lead me to want to create new CSS for it. I'm exactly sure how to handle the CSS for these cases where we wrap an existing thing with something that gives it a more specific purpose.

**Comment by ara4n** [comment]
turns out the confusion here was actually that Tooltip isn't a generic Tooltip but a generic button which happens to emit RoomTooltips. so we're fine now it's renamed TooltipButton - thanks!

**Pull request merged**
