### PR TITLE
Move compact layout to labs

### PR DESCRIPTION
**Pull request by JorikSchellekens**
Design wants to move this away from the available settings

https://www.figma.com/file/HjeMwr2l0kfJDyP3IyiAeu/Text-Settings?node-id=20%3A0

Depends on https://github.com/matrix-org/matrix-react-sdk/pull/4728

### CODE REVIEW

**Comment by t3chguy** [comment]
This is going to upset a lot of people :(

**Comment by JorikSchellekens** [comment]
I'll see if we can move it to the advanced section instead

**Comment by jryans** [comment]
Given that the code here will change significantly depending on whether it's labs vs. advanced, I think it makes more sense to resolve that first. @JorikSchellekens, any reply from design on this? If nothing yet, please add it to their [backlog board](https://github.com/matrix-org/riot-artwork/projects/2) and perhaps mention in design internal as a (hopefully) quick request.

Like @t3chguy, I am concerned this will enrage current users of this setting, since it would become inaccessible on release if it's part of labs.

**Comment by JorikSchellekens** [comment]
Design were reluctant at first but since t3chguy and I were pretty vocal about it they have put it as a note on the design board. I'm strongly advocating to put it under advanced since that would keep continuity with what we already have (and then we could keep the same setting name, preserving continuity for people with this setting enabled)

**Comment by nadonomy** [comment]
@JorikSchellekens we'd be ok to expose this in advanced in the new appearance settings. It isn't clear to me though— would what we were previously calling 'compact' apply to both what we're now calling 'compact' & 'modern'?

**Comment by JorikSchellekens** [comment]
What we previously called 'compact' only applies to our new 'modern'

**Comment by nadonomy** [comment]
> @nadonomy What we previously called 'compact' only applies to our new 'modern'. So the setting for our previous 'compact' would be disabled if the current 'compact (irc layout)' is selected.

Ok, that complicates things slightly, in that case I've expanded the designs here:

https://www.figma.com/file/HjeMwr2l0kfJDyP3IyiAeu/Text-Settings?node-id=0%3A1

**Pull request closed without merging**
