### PR TITLE
Network Dropdown - Remember queried remote servers in dropdown list

### PR DESCRIPTION
**Pull request by pik**
Addresses #3770. If a remote-server was queried and a valid (non-error) response was returned, add it to the serverList in the Network Dropdown.

### CODE REVIEW

**Comment by turt2live** [comment]
This is probably feature creeping, but it would be nice to have the servers persist reloads, and to have some way to remove them from the list (and furthermore ordering). Not sure how others feel about this though.

**Comment by t3chguy** [comment]
having it persist reloads would be easy by using the UserSettingsStore class

**Comment by pik** [comment]
> but it would be nice to have the servers persist reloads, and to have some way to remove them from the list
 
Yeah, the reason I didn't add persistence in this PR is because that would require removal and I'm not 100% on the UI for the later, the easy approach e.g. (but than you have 2 UI actions on what is technically one drop-down item which is not ideal): 

screenshot from 2017-05-15 11-01-47

Alternatively you add an edit network-list button and that gives you a different kind of menu than the select drop-down, perhaps even custom name specification for the servers etc. (more feature creep?)

**Comment by turt2live** [comment]
The feature creep could probably end at some kind of section in the overused User Settings page. Something like this:

---------
### Directory Servers
1. matrix.org ............. icon-arrow-down-b-128 remove-icon-png-24
2. t2l.io ........................ icon-arrow-up-b-128icon-arrow-down-b-128 remove-icon-png-24
3. t2bot.io .................. icon-arrow-up-b-128 remove-icon-png-24
---------

Additionally, the room directory wouldn't have the delete icons - maintaining the single responsibility of being an option.

As mentioned though, this is feature creepy :p

**Comment by turt2live** [comment]
Thanks for the PR @pik - the code has changed quite a lot in the last few years, and our designer will almost certainly want to look this over/solve this. For the time being, we're closing this and can always reference it when the time comes.

**Pull request closed without merging**
