### PR TITLE
Rxl881/parallelshell

### PR DESCRIPTION
**Pull request by rxl881**
With recent versions of node / npm (node v8.4.0, npm v5.3.0), npm run start fails with the following error:

```
richard@MacBook-Pro:~/vector/riot-web$npm run start

> riot-web@0.12.1 start /Users/richard/vector/riot-web
> parallelshell "npm run reskindex:watch" "npm run start:res" "npm run start:js"

child_process.js:400
    throw new TypeError('"cwd" must be a string');
    ^

TypeError: "cwd" must be a string
    at normalizeSpawnArguments (child_process.js:400:11)
    at exports.spawn (child_process.js:487:38)
    at /Users/richard/vector/riot-web/node_modules/parallelshell/index.js:92:17
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/Users/richard/vector/riot-web/node_modules/parallelshell/index.js:91:6)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! riot-web@0.12.1 start: `parallelshell "npm run reskindex:watch" "npm run start:res" "npm run start:js"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the riot-web@0.12.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/richard/.npm/_logs/2017-08-24T11_07_22_099Z-debug.log
```

Updating parallelshell to v3.0.1 fixes this.

### CODE REVIEW

**Comment by t3chguy** [comment]
See https://github.com/matrix-org/matrix-react-sdk/pull/1338#pullrequestreview-58602322
# Blocked on keithamus/parallelshell#60

**Comment by Nostradamos** [comment]
Current way to fix this is by installing the version 3 of parallelshell or downgrading from node 8.
```npm i parallelshell@3.x```
Thanks @t3chguy

**Comment by rxl881** [comment]
Thanks @t3chguy I've updated the dep. as suggested and checked in package-lock.json as discussed in #riot-dev.

@dbkr - Are you happy that this is good to go?

**Comment by rxl881** [comment]
Travis build is (now) failing with spinner stuck error. @lukebarnard1 suggested that this is a known error and can probably be safely ignored.

**Pull request merged**
