### PR TITLE
Document cross_origin_renderer_url

### PR DESCRIPTION
**Pull request by dbkr**

### CODE REVIEW

**Comment by NegativeMjark** [comment]
Maybe link to https://github.com/matrix-org/usercontent ?

**Comment by NegativeMjark** [comment]
Otherwise LGTM.

**Comment by dbkr** [comment]
Done

**Comment by rubo77** [comment]
The information in the README should be enhanced. I have no clue what this should be about and how you should configure it.

Maybe add an extra helpfile that explains why and how to configure this.

**Pull request merged**
