### PR TITLE
New Light High Contrast Riot Theme

### PR DESCRIPTION
**Pull request by tessgadwa**
Submitted in response to Issue #2300 .  Based on feedback from Alan Day and others, refined the CSS from the original PR submitted March 14 to:

- Make body text less heavy
- Condense vertical spacing of text

** Please ignore the previous two closed pull requests submitted for this issue today. **

### CODE REVIEW

**Comment by nshopik** [comment]
Any chance to have screenshot preview? :)

**Comment by tessgadwa** [comment]
@nshopik here is the screenshot preview.

screen shot 2017-03-20 at 4 20 47 pm

**Comment by tessgadwa** [comment]
Disclaimer: this was my first PR ever. Let me know if I need to branch from Develop instead of Master.

**Comment by tessgadwa** [comment]
Signed-off-by: Tess Gadwa <info@yesexactly.com>

**Comment by t3chguy** [comment]
https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.rst#how-to-contribute

**Comment by lukebarnard1** [comment]
Hey @tessgadwa, this does indeed need to be based off develop. So you'd be merging your develop (or feature branch) into riot-web develop.

**Comment by tessgadwa** [comment]
Hi Luke, I am closing and resubmitting (off develop) so I can base on the newest develop build of Riot. Take a look!

**Pull request closed without merging**
