### PR TITLE
Add AppImage target to Linux build

### PR DESCRIPTION
**Pull request by aidalgol**
Tell Electron Builder to build an AppImage as well as a Debian package.

Signed-off-by: Aidan Gauland aidalgol+ghpr@fastmail.net

### CODE REVIEW

**Comment by probonopd** [comment]
What is holding this back?

**Comment by jryans** [comment]
As described in the the related issue #4766, I believe the situation is the core team doesn't currently have bandwidth to support additional release formats and the extra steps they entail. We can leave the issue open to capture feedback on the topic.

I don't believe there's a need to keep this PR itself open, since the core team doesn't appear ready to take on this change at this time.

**Comment by zilti** [comment]
You can drop the .deb package. It's not needed anymore if you provide an AppImage, and an AppImage is easier to build.

**Comment by chaperonRose** [comment]
Is there any news about providing an AppImage ?

**Pull request closed without merging**
