### PR TITLE
Push-to-Talk Support for Jitsi

### PR DESCRIPTION
**Pull request by anoadragon453**
Implements the riot-web portion of Push-to-Talk support for Jitsi voice and video calls. The matrix-react-sdk portion is https://github.com/matrix-org/matrix-react-sdk/pull/2280.

Adds a new native node addon, `iohook`, which is used for listening to shortcuts globally, meaning even when Riot is minimized. As such, iohook needs to be compiled, however like most native node addons, compiled versions for your platform are downloaded during `npm install` for you. The idea is you should never have to compile your own version unless you are using an unsupported platform. The currently supported platforms are Windows, Mac and Linux, however I am unsure what the support is for *BSD.

In terms of security, `iohook` is set to stop itself if it is no longer in charge of any shortcuts. It will only enable itself during a Jitsi call or while recording a new shortcut in settings. While recording a new shortcut, iohook will report every keyboard shortcut that is pressed on the keyboard. This is necessary for shortcut recording. However, if Riot is minimized or otherwise somehow removed from focus while recording a shortcut, the recording session will end.

All of the security functionality is controlled by the Main process, with all of the Renderer processes acting like unprivileged clients. Thus, assuming a security flaw like an XSS only gives you access to functions in the Renderer process, no malicious keylogging should be possible.

The code is set up to allow for any global shortcut to be registered, not just those regarding Push-To-Talk functionality. However, the amount of shortcuts that can be registered at one time is currently controlled by `const keybindingRegistrationLimit`, which is set to 1, so this limit will need to be raised if any future functionality need be added.

### CODE REVIEW

**Comment by dbkr** [comment]
Ah - so the thing is that our build system for the electron builds doesn't support native dependencies (we do all our builds on OS X and it can't cross-compile). This might require us getting separate windows, mac and linux build boxes for the electron app. It was bound to happen sooner or later, but it might not be fast I'm afraid.

**Comment by anoadragon453** [comment]
@dbkr even those that download builds of the native dependencies already like in this case?

**Comment by anoadragon453** [comment]
Now that electron Riot builds have become possible on our build infrastructure, this will become active again.

**Comment by anoadragon453** [comment]
Changes all done wooooooo.

CI needs to be updated, but if you want to test locally: download and extract 
[this file](https://github.com/vector-im/riot-web/files/2912809/iohook.zip) (native node module) and place iohook.node in `riot-web/electron_app/node_modules/iohook/builds/electron-v69-linux-x64/build/Release/iohook.node`.

And then building should work. We need to get our CI to build it for each platform basically.

**Comment by murat-aksoy** [comment]
PTT is just working on electron builds? Can I use it for web UI?

**Comment by anoadragon453** [comment]
I'm afraid not, as websites aren't allowed to access keystrokes when the browser is minimized.

You can however use the space bar for push to talk if you have the jitsi window focused.

**Comment by almamun-dev** [comment]
Hi, one of my client needs private instant Messaging software like whatsapp. is it possible to develop riot for a private company. Please mail me, if anyone can solve my problem. Email: haydenj951@gmail.com ll skype: almamun.dev ll Whatsapp: +8801723894682

**Comment by ara4n** [comment]
what remains here? just getting CI working for desktop? is that actually a hard blocker?

**Comment by BloodyIron** [comment]
@ara4n @anoadragon453 I too would like to know ;)

PTT FTW PLS! :D

**Comment by anoadragon453** [comment]
Windows CI. It needs to be built on all three platforms. I was waiting til Tuesday to try and set it up.

**Comment by Half-Shot** [comment]
Btw, I notice that https://github.com/wilix-team/iohook/blob/master/CHANGELOG.md#v046 includes a windows build fix that was released 9 days ago. Does that improve things?

**Comment by anoadragon453** [comment]
Maaaybe. I think I'm still having an issue with getting the build tools working though.

There's also still this issue: https://github.com/wilix-team/iohook/issues/167 but apparently there's a workaround https://github.com/justadudewhohacks/opencv4nodejs/issues/564

**Comment by anoadragon453** [comment]
This PR has been switched to a local branch: https://github.com/vector-im/riot-web/pull/10369

**Pull request closed without merging**
