### PR TITLE
Piwik Analytics

### PR DESCRIPTION
**Pull request by t3chguy**
# ~~[IN PROGRESS]~~ [NEEDS REVIEW]
Comments about analytics/tracking here welcome.
Especially useful would be ones which help me spot useful things to track to understand userflow better.

At initial this is extremely basic but provides a rock solid base that anything can hook into to send events to Piwik.

dep[matrix-org/matrix-react-sdk/pull/948]

Build available at https://riot.ovh/builds/piwik
Room/User data is `<redacted>` so feel free to log in and help test analytics.

nts: based on 6a7daaf6c4a9526068bf6a4595e063e87e0b6a36

### CODE REVIEW

**Comment by ara4n** [comment]
this is already better than what we had with GA, so i'd feel inclined to merge it asap and see how the data looks.  I wonder if we should provide an option to disable analytics other than via DNT.  (Also I wonder if DNT is the right thing to use, given we're not tracking the user cross-site, which is I think what DNT tries to avoid...).

Can you put some examples in config.json.sample of what the piwik config should look like?

**Comment by t3chguy** [comment]
@ara4n 
I will swap out DNT for a localStorage flag toggled in User Settings
also gonna make the statistics more user readable e.g `RightPanel` -> `Right Panel`
and will have to change the page tracking to track the url in a redacted fashion so that things like transition graphs (useful for user flow?) work instead of them thinking each page is just a reload of the previous

Sample config added

**Comment by ArchangeGabriel** [comment]
Also DNT wouldn’t work for Electron, right?

**Comment by t3chguy** [comment]
@ArchangeGabriel good point, maybe my subconcious wanted to force analytics on people :P

**Comment by ara4n** [comment]
ok, will hold off until DNT is switched for synced settings.

**Comment by t3chguy** [comment]
for continuity: https://matrix.to/#/!DdJkzRliezrwpNebLk:matrix.org/$14960598143240955KwWRv:matrix.org

**Comment by ara4n** [comment]
@t3chguy lmk when i can review/merge. this doesn't have to have all possible metrics present from the outset - would be much more useful to just get it into the RC, which we're planning on cutting today (Tuesday)

**Comment by t3chguy** [comment]
@ara4n ready for review :D

**Comment by ara4n** [comment]
lgtm

**Pull request merged**
