### PR TITLE
Styling for apps / widgets

### PR DESCRIPTION
**Pull request by rxl881**

### CODE REVIEW

**Comment by Kegsay** [comment]
Travis is failing with:
```
Error: Cannot find module 'boom'
```

**Comment by Kegsay** [comment]
Otherwise LGTM.

**Comment by t3chguy** [comment]
I have had that boom error randomly, it disappears after an undefined amount of merges of develop back into the branch.
TravisR and I are thinking its down to some weirdness with CI rather than the code

**Comment by Kegsay** [comment]
Exciting. Thanks for letting me know.

**Pull request merged**
