### PR TITLE
Fix Electron SSO handling to support multiple profiles

### PR DESCRIPTION
**Pull request by t3chguy**
Fixes https://github.com/vector-im/riot-web/issues/12932
Requires https://github.com/vector-im/riot-desktop/pull/67

### CODE REVIEW

**Comment by t3chguy** [comment]
> If we could limit it to only being subdirectories of appData that would make it a bit simpler.

we can't though because someone might use `--profile-dir`: https://github.com/vector-im/riot-desktop/blob/9ebf2171600a0388c7a34ee67d8abfdbbcc431a1/src/electron-main.js#L78

we could encrypt it and urlencode to prevent it being abused

**Comment by dbkr** [comment]
I still have bit of a bad but nonspecific feeling: the key used isn't particularly secure given the HS knows what platform the user is on, and if it's Linux, "/opt/riot-desktop/Riot" is a pretty good guess. I also have a general feeling of nervousness around having bits of crypto code, using different crypto primitives, hanging around for less-oft-used features.

Thinking more about this, one option could be to store currently active SSO sessions with their profile directories in the main profile and then send an sso session ID as a param, looking it up in the map when it comes back?

**Comment by t3chguy** [comment]
I like that idea

**Comment by t3chguy** [comment]
>  "/opt/riot-desktop/Riot" is a pretty good guess.

fwiw, its not, the config is in `/home/$USER/.config/Riot-$PROFILE/...`

**Comment by t3chguy** [comment]
Will create a matching PR for riot-desktop before landing as to not break nightlies

**Pull request merged**
