### PR TITLE
Add riot-desktop shortcuts for forward/back matching browsers&slack

### PR DESCRIPTION
**Pull request by t3chguy**
Fixes https://github.com/vector-im/riot-web/issues/12920
Requires https://github.com/matrix-org/matrix-react-sdk/pull/4392
Requires https://github.com/vector-im/riot-desktop/pull/68

Matches browser default shortcuts for forward/back and also Slack

image

### CODE REVIEW

**Comment by Valodim** [comment]
*thank you* :+1:

**Comment by t3chguy** [comment]
I already wired that app-command years ago.
image


Yup I will port to riot-desktop also

**Comment by t3chguy** [comment]
> To make things more complex, cmd+left/right also work as back/forward in chrome on Mac (and indeed is what I use). Unsure if we want to support this to be consistent with chrome.

Hmm, but aren't cmd + left/right used for text field jumping between words?

**Comment by t3chguy** [comment]
So it seems like it may be an unpopular shortcut https://superuser.com/questions/1367750/how-to-prevent-command-arrow-keys-from-navigating-macos-chrome-forward-backward

**Pull request merged**
