### PR TITLE
Specify Node version in package.json

### PR DESCRIPTION
**Pull request by martindale**
While testing and deploying to several different environments, I found it useful to indicate which version of Node is expected in `package.json`.  Following `README.md`, I've specified `>= 6.3.0` here — though it may be safe to upgrade to `8.0.0` or beyond.  Haven't run into any issues so far.

### CODE REVIEW

**Comment by MTRNord** [comment]
Please commit agains the develop branch and not against master

**Comment by aaronraimist** [comment]
Do you want to update this PR to the new version of node (and npm) specified in the README so it can be merged?

> Install or update node.js so that your node is at least v8.12.0 (and npm is at least v5.x).

**Comment by jryans** [comment]
Thanks for making this contribution a while back.

We are now targeting Node 10 and later. Would you like to update this PR (again...)? I'll do my best to review it quickly.

Please also update the PR or each commit with your sign off as described in [CONTRIBUTING.rst](https://github.com/matrix-org/matrix-js-sdk/blob/develop/CONTRIBUTING.rst).

**Comment by almamun-dev** [comment]
Hi, one of my client needs private instant Messaging software like whatsapp. is it possible to develop riot for a private company. Please mail me, if anyone can solve my problem. Email: haydenj951@gmail.com ll skype: almamun.dev ll Whatsapp: +8801723894682

**Comment by jryans** [comment]
Since there hasn't been a reply in a while, I don't think there's a need to keep this PR open in this state, as we can always find the code here again if needed. If you are still interested in pursuing this change, please discuss with us in #riot-dev:matrix.org to find a good approach forward.

**Pull request closed without merging**
