### PR TITLE
Actually Verticaly Center the red cross

### PR DESCRIPTION
**Pull request by MTRNord**
Just a minimal Css fix

### CODE REVIEW

**Comment by ara4n** [comment]
the X is centred for me already - how does it look to you?  Adding a random offset is unlikely to be the right fix here; if it needs to be centred correctly then we should get the CSS to position it in the centre rather than at a fixed offset.

**Comment by MTRNord** [comment]
For me it is a few Pixel lower than the vertical center. Maybe because of the element nesting. The text left of it is centered

**Comment by MTRNord** [comment]
For me this looks a slight bit to low 
image

PS I use Chrome 58.0.3029.110 (64-bit) on Win 10

**Comment by MTRNord** [comment]
I did a measure with Page Ruler and it says on the top it has 20px until the Container and on the bottom it only has 16px Shouldn't it be about 17.5px on both? (But yes that also says my padding is wrong)

**Comment by ara4n** [comment]
right. on macOS it's okay, so I suspect the actual problem here is that we're making assumptions based on font metrics which vary slightly per-platform. if you fix it by offsetting it on windows you'll break it on macOS.  the correct fix will be to use CSS to actually centre it instead.

**Comment by MTRNord** [comment]
@ara4n propably a normalize css would help?

**Pull request closed without merging**
