### PR TITLE
Use CSS to stop greyed Right/LeftPanel UI from being interactable

### PR DESCRIPTION
**Pull request by lukebarnard1**
Fixes vector-im/riot-web#2073

### CODE REVIEW

**Comment by lukebarnard1** [comment]
Yep, you're absolutely right. Being allowed this level of flexibility with opacities of the different panels is unnecessary imo. Let's have a `disabled` on `LeftPanel` and `RightPanel` that applies a CSS class that can do the opacity and pointer events (I think it's fine to do this with CSS tbh, so long as everyone is aware of what pointer-events does) and modify `ui_opacity` to be two different dispatches `fade_side_panels` and `unfade_side_panels`.

WDYT?

**Comment by t3chguy** [comment]
Forwarding does some funky stuff with fading just the right panel and needing to leave access to the left panel as thats how you select the room to forward to
having no granularity in those dispatches doesn't sound ideal for that

**Comment by lukebarnard1** [comment]
@t3chguy has a point there and some `ui_opacity` dispatches need to fade the middle panel whereas others don't. So I propose we keep the granularity but drop the `opacity` prop and we can use a `mx_fadable_faded` class instead.

**Comment by dbkr** [comment]
yeah, this sounds like a winner then

**Pull request merged**
