### PR TITLE
Add Japanese (#7599)

### LINKED ISSUE #7599: Japanese missing in language selection
A Japanese resource file (riot-web/src/i18n/strings/ja.json) exists. But there is no Japanese as 'Choose a language'. 

Please add the following line if it's ok.
/riot-web/scripts/copy-res.js
INCLUDE_LANGS
{'value': 'ja', 'label': '日本語'},

And when installed in windows Japanese version, Riot-Desktop is displayed in English. it will be better if it's displayed in Japanese from the beginning without language selection as Riot-Android do so.

### PR DESCRIPTION
**Pull request by aaronraimist**
Fixes #7599 

Thank you @kava2108 (and others)!!! 🎉

### CODE REVIEW

**Comment by turt2live** [comment]
🎉 yay! More languages!

I'm electing Dave to take a look at this to make sure it's all that is needed to make this happen.

**Comment by t3chguy** [comment]
I'm 99% sure this is all the necessary magic

**Comment by turt2live** [comment]
So am I, but I'd rather someone else double check it just in case. It also helps make this a PR for "oh you want to add a language? Copy this: [link]".

**Comment by dbkr** [comment]
yep, this is good - thanks!

**Pull request merged**
