### PR TITLE
Workaround menu toggling with layout change key bug

### LINKED ISSUE #4345: After update, every pressing 'alt' key opens the top menu
> this is ANNOYING BUG, for example, alt+shift combination is the most popular for change keyboard layout, alt+tab for task switching.

Says user on rageshake 198 on Riot Desktop 0.10.1 on Linux

### PR DESCRIPTION
**Pull request by nekomiko**
Fixes #4345 bug.

### CODE REVIEW

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/riot-web/pull/4623
wat

**Comment by nekomiko** [comment]
Sorry, I just want any of these to be merged.

**Comment by t3chguy** [comment]
then +1 the existing PR

closing as Duplicate

**Comment by MurzNN** [comment]
So round 5000 pull goes duplicate :(

**Comment by t3chguy** [comment]
exciting in a way, my first duplicate PR close :P

**Pull request closed without merging**
