### PR TITLE
Optimized image assets by recompressing without affecting quality.

### PR DESCRIPTION
**Pull request by MacLemon**
Optimized image assets by recompressing PNGs with various tools that save on filesize and unnecessary metadata as well as removing unnecessary comments from SVGs.
In total this saves 388kB of about 809kB of images (leaving images at only 421kB in total).
This will help cutting down initial loading time of Riot/Web.

Here's the exact breakdown of savings per file.
Screen Shot 2020-04-05 at 15 28 52

### CODE REVIEW

**Comment by turt2live** [comment]
@MacLemon is it possible to get sign off on these changes per the contributing guidelines?

Just needs a comment here with the following template:
```
Signed-off-by: Your Name <email@example.org>
```

**Comment by MacLemon** [comment]
Signed-off-by: MacLemon <git@maclemon.at>

**Comment by MacLemon** [comment]
I'm using a tool called [ImageOptim](https://imageoptim.com/mac) for the Mac. It's a very convenient wrapper around a bunch of tools that basically let's you brute-force the smallest possible image size without compromising quality.

For PNGs it uses:
- Zopfli
- PNGOUT
- OxiPNG
- AdvPNG
- PNGCrush

For SVGs:
- svgcleaner
(and Optionally SVGO, which I didn't use here)

For JPEGs:
- JPEGOptim
- Jpegtran
- Guetzli

For GIFs:
- gifsicle

It doesn't allow for configuring each of the compressors in detail, but in my experience this gives you a very good result by “just throwing a lot of CPU cycles” at the images.

I'll check if I can bend `svgcleaner` to your requirements until then I guess it's most efficient to just use the optimized PNGs.

**Comment by MacLemon** [comment]
I just reverted the SVGs to their former, unoptimized state and only kept the JPGs/PNGs for now. No idea why that now seems to breaks things. I have no idea what I did wrong here.

**Comment by jryans** [comment]
@MacLemon Thanks! For the test failures, I think it's because the other repos are requiring things that are merged to your branch. Can you try merging the develop branch into yours?

**Pull request merged**
