### PR TITLE
use domain config json as override instead of one or the other

### LINKED ISSUE #6843: Deploy-specific riot config files don't override defaults
When you start up a riot.im on example.im it checks for a config file `config.example.im.json`. However, if it finds this, it uses it as the only config file (rather than falling back on `config.json` for defaults).

For running multiple homeservers, it would be useful if config.json could provide the defaults and the deploy-specific file have just the deploy-specific overrides.

### PR DESCRIPTION
**Pull request by t3chguy**
fixes #6843

will result in one additional web request (in envs where domain config does exist), but in instances where the domain config does not exist will actually be faster as they get loaded concurrently

Signed-off-by: Michael Telatynski <7t3chguy@gmail.com>

### CODE REVIEW

**Comment by t3chguy** [comment]
It also fixes the "WHITE SCREEN OF DOOM" you see when you have an invalid config json or no config json, which was unfriendly because SdkConfig.put throws if you pass it undefined and for some reason the "friendlier" message is only after SdkConfig.put

**Comment by dbkr** [comment]
We'll have to have a think about how we switch over from the current system to this, since if people have both config files in place, it'll be quite surprising if the once using the domain specific one suddenly inherits a load of extra config.

**Comment by t3chguy** [comment]
If this is going to be blocked a while it might be nice to cherry-pick https://github.com/vector-im/riot-web/pull/6844/commits/026a0722786ebd04a5e695c9899f694151d146b8 into its own PR as thats a useful thing to have regardless.

**Comment by turt2live** [comment]
fwiw, this is a thing I wrote: https://github.com/homeserver-today/react-sdk-config-server

The use case for #6843 is homeserver hosting, and react-sdk-config-server is specifically written for that use case :p

**Comment by jryans** [comment]
@t3chguy What's the state of this old PR? Should it be reviewed or closed?

**Comment by t3chguy** [comment]
Well it fixes an issue open by Tom but there are concerns that it'd break existing behaviour for people using both config files. @lampholder comment please

If this PR gets closed then the issue should too.
I can fix merge conflict if this is confirmed to still be desired

**Comment by t3chguy** [comment]
Clearly this issue isn't actually wanted to be solved.

**Pull request closed without merging**
