### PR TITLE
Remove electron_app as we now have riot-desktop repo

### PR DESCRIPTION
**Pull request by t3chguy**
Requires https://github.com/vector-im/riot-desktop/pull/81

### CODE REVIEW

**Comment by t3chguy** [comment]
Paging @ArchangeGabriel
is your arch stuff using the riot-desktop repo yet?

https://git.archlinux.org/svntogit/community.git/tree/riot/repos/community-x86_64/PKGBUILD seems to look like it isn't

**Comment by ArchangeGabriel** [comment]
Yes, I just didn’t had time to push 1.6 yet. Currently doing so. ;)

**Comment by t3chguy** [comment]
Will block this until @ArchangeGabriel confirms that their AUR is up to date to not break any installations before then

**Comment by ArchangeGabriel** [comment]
Actually @t3chguy this is not an AUR package anymore, but an actual Arch package (since early 2017). So the PKGBUILD being broken doesn’t mean that people can’t install, at all: the package is available as “binary”. :) Thanks to the reproducible build effort, we are even discovering packages that don’t build for years, but never had to be recompiled for quite some time. ;)

**Comment by t3chguy** [comment]
Ah that's cool, I know very little about Arch but interesting :)

**Comment by rajil** [comment]
@ArchangeGabriel Seems the riot-desktop is out of date. Any love on the package is appreciated.

**Comment by jryans** [comment]
Let's move the Arch discussion to #riot-web:matrix.org or similar.

**Pull request merged**
