### PR TITLE
Reduce rageshake log size to 1MB

### PR DESCRIPTION
**Pull request by richvdh**
... 50MB turned out to be quite a lot.

### CODE REVIEW

**Comment by Kegsay** [comment]
I based 50MB on having a look at general riot-web log spam over time and trying to give a month or so leeway to account for E2E failures which can occur a long time before the bug report gets submitted. Turning this down to 1MB may not be enough to diagnose these problems.

Are you really sure you want to do this?

**Comment by richvdh** [comment]
well, no, but I think most people would be surprised at just how far back the logs that we are submitting go. Example: https://github.com/matrix-org/riot-web-rageshakes/issues/107, which goes back over two months.

a few days seems a more sensible threshold than a couple of months to me. Sure, it won't help diagnose olm issues which lurk unnoticed for ages, but I think it's a sensible tradeoff.

**Comment by Kegsay** [comment]
That's not what this PR is doing, capping based on size != capping based on time which is what it sounds like you really want to do.

**Comment by richvdh** [comment]
> That's not what this PR is doing, capping based on size != capping based on time which is what it sounds like you really want to do.

I appreciate that. But it's not a bad approximation and I thought this would be an easy change :/

**Comment by Kegsay** [comment]
I don't think it's a good idea personally, but obviously you think it's a trade-off worth making.

LGTM

**Comment by richvdh** [comment]
I don't promise I won't change my mind and want to increase it a bit, or improve the logic as you suggest so that it is time-limited as well as/instead of size-limited.

**Pull request merged**
