### PR TITLE
Enable cross-signing on /develop

### PR DESCRIPTION
**Pull request by t3chguy**

### CODE REVIEW

**Comment by jryans** [comment]
Waiting for internal alignment that we've polished things enough for exposure to develop.

**Comment by jryans** [comment]
This is blocked on clarifying device name, ID in toasts, as well as changing to devices -> sessions in Settings copy (will PR now).

**Comment by t3chguy** [comment]
1 part done: https://github.com/matrix-org/matrix-react-sdk/pull/3978

**Comment by jryans** [comment]
Last blocked PR: https://github.com/matrix-org/matrix-react-sdk/pull/3980

**Comment by jryans** [comment]
Blocked PRs completed, waiting for CI to push them live on develop.

**Comment by jryans** [comment]
I'll merge this now, and wait to deploy once develop is confirmed ready.

**Comment by jryans** [comment]
This is now live on develop! 🎉

**Pull request merged**
