### PR TITLE
Fix menu on change keyboard language issue #4345

### PR DESCRIPTION
**Pull request by MurzNN**
Fix activating menu when changing keyboard language / layout  via Alt-Shift, Alt-Ctrl, Alt-CapsLock, and Alt-Space on issue #4345

### CODE REVIEW

**Comment by t3chguy** [comment]
1. Needs sign off
2. Please merge develop back into this, the branch is too old and has old testing stuff which is making it fail

Apart from that and testing, looks good :)

**Comment by MurzNN** [comment]
I change base to develop, this is my first pull request in Github :) hope now I do all right.

**Comment by t3chguy** [comment]
you need to clone it locally,
```bash
git remote add upstream https://github.com/vector-im/riot-web
git fetch upstream
git checkout patch-1
git pull upstream develop
git push
```

You also need to look at https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.rst#sign-off

**Comment by lukebarnard1** [comment]
@MurzNN please read the contributing readme and do a sign-off. Also, this PR might not fix the issue entirely according to https://github.com/vector-im/riot-web/issues/4345#issuecomment-318269417

**Comment by MurzNN** [comment]
Signed-off-by: Alexey Korepov <MurzNN@gmail.com>
- this comment is enough for sign-off
About https://github.com/vector-im/riot-web/issues/4345#issuecomment-318269417 - it is local problem, not in Riot side.
But I can't understand how to do `git checkout patch-1`
After `git fetch upstream` I see that my patch is already applied to source in my local copy, but I don't see that it is applied in `develop` branch.

**Comment by t3chguy** [comment]
I guess I'll do it...

**Comment by dbkr** [comment]
What this actually does is add accelerators to the menus, although beyond it being a Windows convention, the only reference I've found to it being a thing in electron is https://github.com/electron/electron/issues/9584

Anyway, I'm happy for our menus to have accelerators on them and it also fixes a bug for reasons we don't understand, great...

**Pull request merged**
