### PR TITLE
Hide inline encryption icons except when hovering over a message

### PR DESCRIPTION
**Pull request by kethinov**
Closes https://github.com/vector-im/riot-web/issues/2882

Depends on: https://github.com/matrix-org/matrix-react-sdk/pull/1707

### CODE REVIEW

**Comment by lukebarnard1** [comment]
Hi @kethinov, could you fix the conflicts here and in your react-sdk PR and then I'll take a look.

**Comment by kethinov** [comment]
Done.

**Comment by kethinov** [comment]
It looks like a recent commit removed all the CSS files. Where should this work go now?

**Comment by kethinov** [comment]
I think I figured it out. Closing in favor of https://github.com/matrix-org/matrix-react-sdk/pull/1845

**Pull request closed without merging**
