### PR TITLE
Change redact -> remove to improve clarity

### PR DESCRIPTION
**Pull request by turt2live**
Addresses #2814

Non-technical users may not understand what 'redact' means and can more easily understand what 'Remove' does. See discussion on vector-im/riot-web#2814 for more information.

Paired with: https://github.com/matrix-org/matrix-react-sdk/pull/831

### CODE REVIEW

**Comment by t3chguy** [comment]
Remove is slightly less clear in its actual action, since the actual content of the message is not removed. (Still visible to admins and whatnot)

**Comment by t3chguy** [comment]
Personally https://github.com/vector-im/riot-web/issues/2814#issuecomment-288474427 makes more sense

**Comment by turt2live** [comment]
After reading the discussion on #2814 it seems like people prefer 'Remove' or 'Delete', as those are terms used almost unanimously in chat clients/other software. 'Retract' to me still feels like something that non-technical users wouldn't understand the implications of, or have to think about what the action is before doing it. Having the user think less about what the button *could* do is important to not have small roadblocks that could result in someone not using Riot.

Granted, the actual implementation is still different from the label. As mentioned in #2814, most users aren't going to care that their message is still legible somewhere, or that it's possible that it doesn't actually remove it from everywhere. They just wanted to delete something they said.

**Comment by ara4n** [comment]
My personal preference here has always been 'delete', with 'hide' used for (in future) hiding messages just from the reader.

But the problem with 'delete' and 'remove' is that it implies the permanence which you normally get from computers when you ask them to remove something - which obviously isn't the case here.  I also agree that 'retract' is clumsy, and that 'redact' is useless for most people.  'recall' makes people think of evil Outlook, but it's at least a familiar model...

Suggestions welcome for alternatives.  I'll ask around too.

**Comment by turt2live** [comment]
Has a decision been made on 'delete' or 'remove' (or other)? Last update was an ask for feedback, and unfortunately it looks like few comments made it this far.

**Comment by turt2live** [comment]
@ara4n 
> Has a decision been made on 'delete' or 'remove' (or other)? Last update was an ask for feedback, and unfortunately it looks like few comments made it this far.

**Comment by ara4n** [comment]
i'm going to make an exec decision to go with 'remove', given it feels somewhat less final than 'delete'.

**Pull request merged**
