### PR TITLE
Sorting of networks within a protocol based on name

### PR DESCRIPTION
**Pull request by ollieh**
#3771

Now it looks like this:
screenshot_2017-05-27_17-27-39

### CODE REVIEW

**Comment by turt2live** [comment]
iirc "matrix.org" is intended to be the parent heading, then all the things with icons are subpoints of matrix.org, just badly shown as such.

**Comment by ollieh** [comment]
Will there ever be multiple headings, or can I just stick it at the top?

**Comment by turt2live** [comment]
It's possible for custom-homeserver folk:
image

(and for others who define their settings correctly... somehow).

**Comment by ollieh** [comment]
Ooh, that makes things rather trickier.

**Comment by ollieh** [comment]
Changed it to just sort between headings, although it feels a bit complicated. I guess it could be simplified if it did this while it was adding them, but I wanted to keep the sorting logic separated in case I changed the behaviour.

**Comment by ollieh** [comment]
Figured out how the list was being constructed and put the sorting logic in there, much neater!

**Comment by t3chguy** [comment]
looks much better than the initial pr diff

**Comment by lukebarnard1** [comment]
Removing my assignment for now as I don't actually know if we want Gitter all the way down there. @ara4n's input would be appreciated.

**Comment by ara4n** [comment]
sorry for missing this months ago - if you need my input please assign it to me... the alphabetised list looks good to me.

**Pull request merged**
