### PR TITLE
add styles for compact layout

### PR DESCRIPTION
**Pull request by uhoreg**
for #109, depends on matrix-org/matrix-react-sdk#986

I started with the styles from https://github.com/vector-im/riot-web/issues/109#issuecomment-284862682, and tweaked it and added a bunch more things, such as:

- tweak spacing for emotes so that the avatars don't collide
- shrunk spacing for URL previews
- shrunk bottom bar (left panel buttons, composer, right panel invite button)
- shrunk notification bar and unread messages bar
- shifted e2e icons and read receipts to be aligned with the new message positions

There may be other things that need tweaking, but I've been using this for most of the day without noticing anything weird.

### CODE REVIEW

**Comment by uhoreg** [comment]
Here, have a screenshot too:
image

**Comment by ara4n** [comment]
There's a bug in mini-avatar vertical offset on showing textualevents which aren't part of a continuation (i think?):
screen shot 2017-06-01 at 15 07 08
I'm failing to spot where that override has been missing

**Comment by ara4n** [comment]
ftr:
> Matthew
> uhoreg: my only concern here is at the maintainability of the overrides
how alarmed would you be if I suggested turning the magic numbers in the overrides at least into variables?
e.g. $compact-event-tile-padding-top rather than 18px or whatever
in the expectation that in future the non-compact-layout magic values would also be sensibly named
and appropriate arithmetic expressions used?
(which would then obviously let folks fine-tune more easily in future)

> uhoreg
Yup, using variables sounds fine to me

**Comment by uhoreg** [comment]
@ara4n I think I've fixed the issue with the mini avatar positioning.

I'm not really a fan of the smaller username.  IMHO it looks a bit off, especially when it's right next to an emote or info event that has the username in normal size

I'll take a look next into how best to make variables for the numbers.

**Comment by ara4n** [comment]
given this is working and the variables are subject to taste, i'm going to merge anyway. not sure what to do about subjective differences in taste about the layout though; i find the smaller username makes the content much more legible, as it makes it clearer that the name is less significant.

**Comment by 4nd3r** [comment]
imho avatars should be bit smaller in compact mode, particularly when timestamps are always shown.

scrot-1496398315

**Pull request merged**
