### PR TITLE
Added styling for copy to clipboard button

### PR DESCRIPTION
**Pull request by ollieh**
Currently using the edit button's image as a placeholder, it needs its own icon.

Paired with https://github.com/matrix-org/matrix-react-sdk/pull/1040

See issue #1974 

Should I have a go at creating one myself, or is there someone responsible for creating the icons?

### CODE REVIEW

**Comment by ollieh** [comment]
What the new icons look like:
newicons

**Comment by ollieh** [comment]
Nice, it appears to be working. I do wonder if it would be worth code blocks having a different background colour than the message when you hover over the message, or a border. Had a little play:
backgroundcolorcode
bordercode

**Comment by ara4n** [comment]
ooh, this is great - thanks! (although i haven't looked at the code yet) the 1px border is a great idea too - can you push the CSS?

**Pull request merged**
