### PR TITLE
Specify a size for URL previews

### PR DESCRIPTION
**Pull request by foldleft**
This is kinda hard to test on the fly, nobody wants to URL-preview localhost

Fixes: https://github.com/vector-im/riot-web/issues/12014

Best only close the ticket once confirmed in prod

### CODE REVIEW

**Comment by foldleft** [comment]
I've poked @nadonomy for feedback

**Comment by nadonomy** [comment]
@foldleft rather than resizing the asset currently being used by the opengraph tags, can we instead just use this?

https://about.riot.im/images/opengraph.png

**Comment by foldleft** [comment]
@nadonomy that's fine, but is the size okay?

**Comment by nadonomy** [comment]
Should be fine— the issue is the aspect ratio rather than the absolute size.

**Pull request closed without merging**
